# Generated by Django 5.2.1 on 2025-05-16 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='email',
            new_name='address',
        ),
        migrations.AddField(
            model_name='contact',
            name='flavor',
            field=models.CharField(default='Vanilla', max_length=12),
            preserve_default=False,
        ),
    ]
