# Generated by Django 5.2.1 on 2025-05-16 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_email_contact_address_contact_flavor'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='quantity',
            field=models.CharField(default=1, max_length=12),
            preserve_default=False,
        ),
    ]
