# Generated by Django 5.2.1 on 2025-05-16 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_contact_address_alter_contact_flavor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='flavor',
            field=models.CharField(max_length=15),
        ),
    ]
